export const styleDefaults = {
  dialogShowed: "bottom",
  pageColor: "rgba(155,155,155,.5)",
  dialogShadow: "3px 25px 27px -29px rgba(0,0,0,0.4)",
  dialogColor: "rgb(255,255,255)",
  fontSize: "16px",
  buttonFontSize: "18px",
  acceptBackgroundColor: "white",
  acceptColor: "black",
  showPreferencesBackgroundColor: "white",
  showPreferencesColor: "black",
  savePreferencesBackgroundColor: "white",
  savePreferencesColor: "black",
  cookieBackgroundColor: "rgb(250,250,250)",
  cookieTypeFontSize: "12px",
  cookieInfoFontSize: "12px",
  cookiePanelHeight: "60px",
  cookieCheckboxPadding: "8px",
};
